defaults: &defaults
  theme_url: http://theme.instedd.org/
  contact_us: http://instedd.org/contact-us/
  contact_us_ilab: http://www.ilabamericalatina.org/contactanos
  report_bug: support@instedd.org
  suscribe_url: http://instedd.us2.list-manage.com/subscribe/post?u=b1404e482b02edd641e6506cf&id=6e0ca202fc
  source_code_url: https://github.com/instedd/pollit/overview
  backlog_url: https://github.com/instedd/pollit/issues?status=new&status=open
  user_group_url: https://groups.google.com/group/instedd-tech
  google_analytics:
  android_gateway_url: https://market.android.com/details?id=org.instedd.geochat.lgw&hl=en

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
